package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"

	"github.com/sxmmie/intro-graphql/errors"
	"github.com/sxmmie/intro-graphql/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	if len(strings.TrimSpace(input.Text)) == 0 {
		return nil, &errors.ValidationError{
			Field:   "text",
			Message: "text cannot be empty",
		}
	}

	if len(input.Text) > 255 {
		return nil, &errors.ValidationError{
			Field:   "text",
			Message: "text cannot exceed 255 characters",
		}
	}

	todo := r.TodoStore.Create(input.Text)

	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodo) (*model.Todo, error) {
	todo := r.TodoStore.Update(id, input.Text, input.Done)
	if todo != nil {
		return nil, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	return r.TodoStore.Delete(id), nil
}

// ToggleTodo is the resolver for the toggleTodo field.
func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	todo := r.TodoStore.Toggle(id)
	if todo != nil {
		return nil, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos := r.TodoStore.GetAll()

	result := make([]*model.Todo, len(todos))

	for i, todo := range todos {
		result[i] = &model.Todo{
			ID:        todo.ID,
			Text:      todo.Text,
			Done:      todo.Done,
			CreatedAt: todo.CreatedAt,
		}
	}

	return result, nil
}

// Todo is the resolver for the todo field
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	todo := r.TodoStore.GetByID(id)

	if todo == nil {
		return nil, &errors.NotFoundError{
			Resource: "Todo",
			ID:       id,
		}
	}

	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

// TodoByStatus is the resolver for the todoByStatus field.
func (r *queryResolver) TodoByStatus(ctx context.Context, done bool) ([]*model.Todo, error) {
	todos := r.TodoStore.GetByStatus(done)

	result := make([]*model.Todo, len(todos))
	for i, todo := range todos {
		result[i] = &model.Todo{
			ID:        todo.ID,
			Text:      todo.Text,
			Done:      todo.Done,
			CreatedAt: todo.CreatedAt,
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
