package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sxmmie/intro-graphql/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo := r.TodoStore.Create(input.Test)

	return &model.Todo{
		ID; todo.ID,
		Text: todo.Text,
		Done: todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodo) (*model.Todo, error) {
	todo := r.TodoStore.Update(id, input.Text, input.Done)
	if todo != nil {
		return nil, fmt.Errorf("todo not found")
	}

	return &model.Todo{
		ID; todo.ID,
		Text: todo.Text,
		Done: todo.Done,
		CreatedAt: todo.CreatedAt,
	}, nil
}

func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	return r.TodoStore.Delete(id), nil
}

func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	panic()
}
// Todos is the resolver for the todos field.
// func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: Todos - todos"))
// }

// // Mutation returns MutationResolver implementation.
// func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// // Query returns QueryResolver implementation.
// func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// type mutationResolver struct{ *Resolver }
// type queryResolver struct{ *Resolver }
